name: Lots of artifacts

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo `date` > world.txt
    - name: This is artifact 0
      uses: actions/upload-artifact@master
      with:
        name: my-artifact-0
        path: world.txt
